### ISSUE TITLE
Missing procedure to install on Sinology disk station DS718+

### ISSUE THREAD

**Issue by hlesueur** [cnbr/lldpd#1]
Hello, 
I'm sorry for this newbie question, but from your "readme" and official website I could not find the right procedure to install on my synology. 
I've tried the "install from source" documented on the website but got lots of errors at the make step -already the ../configure does not work very well
I feel I'm missing some files related to libevent, which seem to be contained on your github page, 
but I absolutely don't know how to either include them properly, or install the whole thing directly from github
Could you please edit a tutorial for non familiar ?
Thanks a lot for your help !

**Comment by cnbr** [comment]
Hello,
follow the Synology Developer Guide to install the Bulding Environment (https://help.synology.com/developer-guide/getting_started/index.html).
Check, that the hardware platform and DSM version that it fits your environment.

Testing the installation with the tmux or nmap example in the toolkit would be helpful to understand the building process.

If it works, clone the lldpd to  toolkit/source/ and start the building process, see https://help.synology.com/developer-guide/create_package/build_and_create_package.html

I tested it with a 216, not everything is perfect but it worked

I wish you success
